name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dashboard code
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: pnpm
      - name: Install package and build
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build
      - name: Archive and upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Yacd-meta
          path: |
            public
          if-no-files-found: error
